#!/usr/bin/env python3
"""Embed Video.metal without touching the output when bytes are unchanged."""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import sys
import tempfile


ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SOURCE = ROOT / "Modules/MediaCore/Shaders/Video.metal"
DEFAULT_OUTPUT = ROOT / "BuildGenerated/ShaderSource.h"


def render_header(content: str) -> str:
    terminator = ')SPMETAL"'
    if terminator in content:
        raise ValueError(f"shader contains raw-string terminator {terminator!r}")
    return (
        "#pragma once\n"
        "// Generated by Scripts/gen_shader_header.py; do not edit.\n"
        "static const char* const kSPShaderSource = R\"SPMETAL(\n"
        + content
        + "\n)SPMETAL\";\n"
    )


def update_header(source: Path, output: Path) -> bool:
    content = source.read_text(encoding="utf-8")
    header = render_header(content)
    try:
        if output.read_text(encoding="utf-8") == header:
            return False
    except FileNotFoundError:
        pass

    output.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{output.name}.", suffix=".tmp", dir=output.parent
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write(header)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, output)
    finally:
        try:
            temporary.unlink()
        except FileNotFoundError:
            pass
    return True


def create_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = create_parser().parse_args(argv)
    try:
        changed = update_header(args.source, args.output)
    except (OSError, ValueError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    state = "generated" if changed else "unchanged"
    print(f"ShaderSource.h {state} ({args.output.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
